### ISSUE TITLE
240811 merge 이슈 문의squash

### ISSUE THREAD

**Issue by Yul0201** [olive-study-club/study-forever#14]
- 1차 PR을 했으나 정상적인 케이스가 아니어서 Squash Merge로 하는 경우 (제가 이미 PR을 올린 것도 합쳐져서 PR을 올리는 것으로 알고 있었는데) comment를 추가로 작성할 수 가 없는 것으로 보여 정상적으로 merge 를 한 게 아닌 것으로 보입니다. (호인님의 comment 작성이 불가한 상태로 보입니다)
혹시 이렇게 잘못 PR을 올린 경우 이를 해소할 수 있는 방법이 있는지 문의드립니다.

**Comment by firewoody237** [comment]
사진 처럼 `Quote Reply`로 남기셔도 됩니다~

<img width="877" alt="스크린샷 2024-08-17 오전 9 38 40" src="https://github.com/user-attachments/assets/ce8d99bd-931c-475d-b002-0636845cfdf5">
